import 'package:design_systems/dino/foundations/token.lineheight.dart';
import 'package:flutter/painting.dart';
import 'package:mix/mix.dart';
import 'package:design_systems/dino/foundations/token.color.dart';
import 'package:design_systems/dino/foundations/token.spacing.dart';
import 'package:design_systems/dino/foundations/token.radius.dart';
import 'package:design_systems/dino/foundations/token.stroke.dart';
import 'package:design_systems/dino/foundations/token.typography.dart';

const $dinoToken = DesignToken();

class DesignToken {
  const DesignToken();
  final DinoColorToken color = const DinoColorToken();
  final DinoSpaceToken spacing = const DinoSpaceToken();
  final DinoRadiusToken radius = const DinoRadiusToken();
  final DinoStrokeToken stroke = const DinoStrokeToken();
  final DinoTypographyToken typography = const DinoTypographyToken();
}

final dinoTheme = MixThemeData(
  textStyles: {
    $dinoToken.typography.headingXXL: const TextStyle(
      fontSize: DinoTextSizeToken.text1100,
      fontFamily: 'Pretendard',
      fontWeight: FontWeight.w700,
      // height: DinoLineHeightToken.lineHeight1100,
    ),
    $dinoToken.typography.headingXL: const TextStyle(
      fontSize: DinoTextSizeToken.text1000,
      fontFamily: 'Pretendard',
      fontWeight: FontWeight.w700,
      // height: DinoLineHeightToken.lineHeight1000,
    ),
    $dinoToken.typography.headingL: const TextStyle(
      fontSize: DinoTextSizeToken.text800,
      fontFamily: 'Pretendard',
      fontWeight: FontWeight.w700,
      // height: DinoLineHeightToken.lineHeight800,
    ),
    $dinoToken.typography.headingM: const TextStyle(
      fontSize: DinoTextSizeToken.text600,
      fontFamily: 'Pretendard',
      fontWeight: FontWeight.w700,
      // height: DinoLineHeightToken.lineHeight600,
    ),
    $dinoToken.typography.headingS: const TextStyle(
      fontSize: DinoTextSizeToken.text500,
      fontFamily: 'Pretendard',
      fontWeight: FontWeight.w700,
      // height: DinoLineHeightToken.lineHeight500,
    ),
    $dinoToken.typography.headingXS: const TextStyle(
      fontSize: DinoTextSizeToken.text300,
      fontFamily: 'Pretendard',
      fontWeight: FontWeight.w600,
      // height: DinoLineHeightToken.lineHeight300,
    ),

    $dinoToken.typography.bodyXXL: const TextStyle(
      fontSize: DinoTextSizeToken.text600,
      fontWeight: FontWeight.w600,
      fontFamily: 'Pretendard',
      // height: DinoLineHeightToken.lineHeight600,
    ),
    $dinoToken.typography.bodyXL: const TextStyle(
      fontSize: DinoTextSizeToken.text500,
      fontWeight: FontWeight.w600,
      fontFamily: 'Pretendard',
      // height: DinoLineHeightToken.lineHeight500,
    ),
    $dinoToken.typography.bodyL: const TextStyle(
      fontSize: DinoTextSizeToken.text400,
      fontWeight: FontWeight.w600,
      fontFamily: 'Pretendard',
      // height: DinoLineHeightToken.lineHeight400,
    ),
    $dinoToken.typography.bodyM: const TextStyle(
      fontSize: DinoTextSizeToken.text300,
      fontWeight: FontWeight.w500,
      fontFamily: 'Pretendard',
      // height: DinoLineHeightToken.lineHeight300,
    ),
    $dinoToken.typography.bodyS: const TextStyle(
      fontSize: DinoTextSizeToken.text200,
      fontWeight: FontWeight.w500,
      fontFamily: 'Pretendard',
      // height: DinoLineHeightToken.lineHeight200,
    ),
    $dinoToken.typography.bodyXS: const TextStyle(
      fontSize: DinoTextSizeToken.text100,
      fontWeight: FontWeight.w500,
      fontFamily: 'Pretendard',
      // height: DinoLineHeightToken.lineHeight100,
    ),

    $dinoToken.typography.detailXXL: const TextStyle(
      fontSize: DinoTextSizeToken.text200,
      fontWeight: FontWeight.w400,
      fontFamily: 'Pretendard',
      // height: DinoLineHeightToken.lineHeight200,
    ),
    $dinoToken.typography.detailXL: const TextStyle(
      fontSize: DinoTextSizeToken.text100,
      fontWeight: FontWeight.w400,
      fontFamily: 'Pretendard',
      // height: DinoLineHeightToken.lineHeight100,
    ),
    $dinoToken.typography.detailL: const TextStyle(
      fontSize: DinoTextSizeToken.text100,
      fontWeight: FontWeight.w500,
      fontFamily: 'Pretendard',
      // height: DinoLineHeightToken.lineHeight100,
    ),
    $dinoToken.typography.detailM: const TextStyle(
      fontSize: DinoTextSizeToken.text75,
      fontWeight: FontWeight.w500,
      fontFamily: 'Pretendard',
      // height: DinoLineHeightToken.lineHeight75,
    ),
    $dinoToken.typography.detailS: const TextStyle(
      fontSize: DinoTextSizeToken.text50,
      fontWeight: FontWeight.w500,
      fontFamily: 'Pretendard',
      // height: DinoLineHeightToken.lineHeight50,
    ),
  },
  colors: {
    $dinoToken.color.black: const Color(0xFF000000),
    $dinoToken.color.white: const Color(0xFFFFFFFF),
    $dinoToken.color.shadow00s: const Color(0x6D758305),
    $dinoToken.color.shadow04s: const Color(0x6D75830A),
    $dinoToken.color.shadow08s: const Color(0x6D758314),
    $dinoToken.color.shadow16s: const Color(0x6D75831F),
    $dinoToken.color.shadow24s: const Color(0x6D758329),
    $dinoToken.color.shadow32s: const Color(0x6D758333),
    $dinoToken.color.shadow36s: const Color(0x6D75833D),
    $dinoToken.color.shadow00e: const Color(0x6D758305),
    $dinoToken.color.shadow04e: const Color(0x6D75830A),
    $dinoToken.color.shadow08e: const Color(0x6D758314),
    $dinoToken.color.shadow16e: const Color(0x6D75831A),
    $dinoToken.color.shadow24e: const Color(0x6D75831F),
    $dinoToken.color.shadow32e: const Color(0x6D75831F),
    $dinoToken.color.shadow36e: const Color(0x6D75831F),
    $dinoToken.color.blingGray25: const Color(0xFFFBFCFD),
    $dinoToken.color.blingGray50: const Color(0xFFF8F9FA),
    $dinoToken.color.blingGray75: const Color(0xFFF1F3F5),
    $dinoToken.color.blingGray100: const Color(0xFFECEEF0),
    $dinoToken.color.blingGray200: const Color(0xFFDFE3E6),
    $dinoToken.color.blingGray300: const Color(0xFFD7DBDF),
    $dinoToken.color.blingGray400: const Color(0xFFB7BEC8),
    $dinoToken.color.blingGray500: const Color(0xFF969FAC),
    $dinoToken.color.blingGray600: const Color(0xFF6D7583),
    $dinoToken.color.blingGray700: const Color(0xFF525965),
    $dinoToken.color.blingGray800: const Color(0xFF2E3137),
    $dinoToken.color.blingGray900: const Color(0xFF11181C),
    $dinoToken.color.blackA25: const Color(0x00000003),
    $dinoToken.color.blackA50: const Color(0x00000008),
    $dinoToken.color.blackA75: const Color(0x0000000D),
    $dinoToken.color.blackA100: const Color(0x00000012),
    $dinoToken.color.blackA200: const Color(0x00000017),
    $dinoToken.color.blackA300: const Color(0x0000001C),
    $dinoToken.color.blackA400: const Color(0x00000024),
    $dinoToken.color.blackA500: const Color(0x00000038),
    $dinoToken.color.blackA600: const Color(0x00000070),
    $dinoToken.color.blackA700: const Color(0x0000007A),
    $dinoToken.color.blackA800: const Color(0x0000008F),
    $dinoToken.color.blackA900: const Color(0x000000E6),
    $dinoToken.color.whiteA25: const Color(0xFFFFFF00),
    $dinoToken.color.whiteA50: const Color(0xFFFFFF03),
    $dinoToken.color.whiteA75: const Color(0xFFFFFF0A),
    $dinoToken.color.whiteA100: const Color(0xFFFFFF0F),
    $dinoToken.color.whiteA200: const Color(0xFFFFFF17),
    $dinoToken.color.whiteA300: const Color(0xFFFFFF21),
    $dinoToken.color.whiteA400: const Color(0xFFFFFF2E),
    $dinoToken.color.whiteA500: const Color(0xFFFFFF40),
    $dinoToken.color.whiteA600: const Color(0xFFFFFF61),
    $dinoToken.color.whiteA700: const Color(0xFFFFFF73),
    $dinoToken.color.whiteA800: const Color(0xFFFFFF96),
    $dinoToken.color.whiteA900: const Color(0xFFFFFFEB),
    $dinoToken.color.blingPrimary25: const Color(0xFFFFFCFB),
    $dinoToken.color.blingPrimary50: const Color(0xFFFEF7F5),
    $dinoToken.color.blingPrimary75: const Color(0xFFFEEFEB),
    $dinoToken.color.blingPrimary100: const Color(0xFFFAE1DA),
    $dinoToken.color.blingPrimary200: const Color(0xFFFAD5CC),
    $dinoToken.color.blingPrimary300: const Color(0xFFF9BBAC),
    $dinoToken.color.blingPrimary400: const Color(0xFFFC9E87),
    $dinoToken.color.blingPrimary500: const Color(0xFFFD7B5B),
    $dinoToken.color.blingPrimary600: const Color(0xFFF94114),
    $dinoToken.color.blingPrimary700: const Color(0xFFDF350B),
    $dinoToken.color.blingPrimary800: const Color(0xFFC72C06),
    $dinoToken.color.blingPrimary900: const Color(0xFF4D1B0F),
    $dinoToken.color.secondaryInfoBlue50: const Color(0xFFEFF6FF),
    $dinoToken.color.secondaryInfoBlue100: const Color(0xFFC0D9F8),
    $dinoToken.color.secondaryInfoBlue300: const Color(0xFF79B0F7),
    $dinoToken.color.secondaryInfoBlue500: const Color(0xFF0D74F6),
    $dinoToken.color.secondaryInfoBlue700: const Color(0xFF234EC6),
    $dinoToken.color.secondarySubInfoNavi100: const Color(0xFFC9D0E1),
    $dinoToken.color.secondarySubInfoNavi300: const Color(0xFF97A2BB),
    $dinoToken.color.secondarySubInfoNavi400: const Color(0xFF717B98),
    $dinoToken.color.secondarySubInfoNavi500: const Color(0xFF505C81),
    $dinoToken.color.secondarySubInfoNavi600: const Color(0xFF324066),
    $dinoToken.color.secondarySubInfoNavi700: const Color(0xFF242F53),
    $dinoToken.color.secondarySubInfoNavi800: const Color(0xFF18223A),
    $dinoToken.color.secondaryPositiveGreen200: const Color(0xFFEAF8F2),
    $dinoToken.color.secondaryPositiveGreen400: const Color(0xFF22C983),
    $dinoToken.color.secondaryPositiveGreen600: const Color(0xFF0AAA66),
    $dinoToken.color.secondaryNegativeRed200: const Color(0xFFFFF3F3),
    $dinoToken.color.secondaryNegativeRed400: const Color(0xFFF96267),
    $dinoToken.color.secondaryNegativeRed600: const Color(0xFFE54147),
    $dinoToken.color.secondaryCautionYellow200: const Color(0xFFFFF8E2),
    $dinoToken.color.secondaryCautionYellow400: const Color(0xFFEFB603),
    $dinoToken.color.secondaryCautionYellow600: const Color(0xFFE17A01),
    $dinoToken.color.brandBlingOranage25: const Color(0xFFFEFCFB),
    $dinoToken.color.brandBlingOranage50: const Color(0xFFFEF8F4),
    $dinoToken.color.brandBlingOranage75: const Color(0xFFFFF1E7),
    $dinoToken.color.brandBlingOranage100: const Color(0xFFFFE8D7),
    $dinoToken.color.brandBlingOranage200: const Color(0xFFFFDCC3),
    $dinoToken.color.brandBlingOranage300: const Color(0xFFFFCCA7),
    $dinoToken.color.brandBlingOranage400: const Color(0xFFFFB381),
    $dinoToken.color.brandBlingOranage500: const Color(0xFFFA934E),
    $dinoToken.color.brandBlingOranage600: const Color(0xFFF76808),
    $dinoToken.color.brandBlingOranage700: const Color(0xFFFC5C17),
    $dinoToken.color.brandBlingOranage800: const Color(0xFFBD4B00),
    $dinoToken.color.brandBlingOranage900: const Color(0xFF451E11),
    $dinoToken.color.brandBlingPimento25: const Color(0xFFFFFCFC),
    $dinoToken.color.brandBlingPimento50: const Color(0xFFFFF8F7),
    $dinoToken.color.brandBlingPimento75: const Color(0xFFFFF0EE),
    $dinoToken.color.brandBlingPimento100: const Color(0xFFFFE6E2),
    $dinoToken.color.brandBlingPimento200: const Color(0xFFFDD8D3),
    $dinoToken.color.brandBlingPimento300: const Color(0xFFFAC7BE),
    $dinoToken.color.brandBlingPimento400: const Color(0xFFF3B0A2),
    $dinoToken.color.brandBlingPimento500: const Color(0xFFEA9280),
    $dinoToken.color.brandBlingPimento600: const Color(0xFFE54D2E),
    $dinoToken.color.brandBlingPimento700: const Color(0xFFDB4324),
    $dinoToken.color.brandBlingPimento800: const Color(0xFFCA3214),
    $dinoToken.color.brandBlingPimento900: const Color(0xFF341711),
    $dinoToken.color.brandBlingRed25: const Color(0xFFFFFCFC),
    $dinoToken.color.brandBlingRed50: const Color(0xFFFFF8F8),
    $dinoToken.color.brandBlingRed75: const Color(0xFFFFEFEF),
    $dinoToken.color.brandBlingRed100: const Color(0xFFFFE5E5),
    $dinoToken.color.brandBlingRed200: const Color(0xFFFDD8D8),
    $dinoToken.color.brandBlingRed300: const Color(0xFFF9C6C6),
    $dinoToken.color.brandBlingRed400: const Color(0xFFF3AEAF),
    $dinoToken.color.brandBlingRed500: const Color(0xFFEB9091),
    $dinoToken.color.brandBlingRed600: const Color(0xFFE5484D),
    $dinoToken.color.brandBlingRed700: const Color(0xFFDC3D43),
    $dinoToken.color.brandBlingRed800: const Color(0xFFCD2B31),
    $dinoToken.color.brandBlingRed900: const Color(0xFF381316),
    $dinoToken.color.brandBlingCrimson25: const Color(0xFFFFFCFD),
    $dinoToken.color.brandBlingCrimson50: const Color(0xFFFFF7FB),
    $dinoToken.color.brandBlingCrimson75: const Color(0xFFFEEFF6),
    $dinoToken.color.brandBlingCrimson100: const Color(0xFFFCE5F0),
    $dinoToken.color.brandBlingCrimson200: const Color(0xFFF9D8E7),
    $dinoToken.color.brandBlingCrimson300: const Color(0xFFF4C6DB),
    $dinoToken.color.brandBlingCrimson400: const Color(0xFFEDADC8),
    $dinoToken.color.brandBlingCrimson500: const Color(0xFFE58FB1),
    $dinoToken.color.brandBlingCrimson600: const Color(0xFFE93D82),
    $dinoToken.color.brandBlingCrimson700: const Color(0xFFE03177),
    $dinoToken.color.brandBlingCrimson800: const Color(0xFFD31E66),
    $dinoToken.color.brandBlingCrimson900: const Color(0xFF3D0D1D),
    $dinoToken.color.brandBlingPink25: const Color(0xFFFFFCFE),
    $dinoToken.color.brandBlingPink50: const Color(0xFFFFF7FC),
    $dinoToken.color.brandBlingPink75: const Color(0xFFFEEEF8),
    $dinoToken.color.brandBlingPink100: const Color(0xFFFCE5F3),
    $dinoToken.color.brandBlingPink200: const Color(0xFFF9D8EC),
    $dinoToken.color.brandBlingPink300: const Color(0xFFF3C6E2),
    $dinoToken.color.brandBlingPink400: const Color(0xFFECADD4),
    $dinoToken.color.brandBlingPink500: const Color(0xFFE38EC3),
    $dinoToken.color.brandBlingPink600: const Color(0xFFD6409F),
    $dinoToken.color.brandBlingPink700: const Color(0xFFD23197),
    $dinoToken.color.brandBlingPink800: const Color(0xFFCD1D8D),
    $dinoToken.color.brandBlingPink900: const Color(0xFF3B0A2A),
    $dinoToken.color.brandBlingPlum25: const Color(0xFFFEFCFF),
    $dinoToken.color.brandBlingPlum50: const Color(0xFFFFF8FF),
    $dinoToken.color.brandBlingPlum75: const Color(0xFFFCEFFC),
    $dinoToken.color.brandBlingPlum100: const Color(0xFFF9E5F9),
    $dinoToken.color.brandBlingPlum200: const Color(0xFFF3D9F4),
    $dinoToken.color.brandBlingPlum300: const Color(0xFFEBC8ED),
    $dinoToken.color.brandBlingPlum400: const Color(0xFFDFAFE3),
    $dinoToken.color.brandBlingPlum500: const Color(0xFFCF91D8),
    $dinoToken.color.brandBlingPlum600: const Color(0xFFAB4ABA),
    $dinoToken.color.brandBlingPlum700: const Color(0xFFA43CB4),
    $dinoToken.color.brandBlingPlum800: const Color(0xFF9C2BAD),
    $dinoToken.color.brandBlingPlum900: const Color(0xFF340C3B),
    $dinoToken.color.brandBlingPurple25: const Color(0xFFFEFCFE),
    $dinoToken.color.brandBlingPurple50: const Color(0xFFFDFAFF),
    $dinoToken.color.brandBlingPurple75: const Color(0xFFF9F1FE),
    $dinoToken.color.brandBlingPurple100: const Color(0xFFF3E7FC),
    $dinoToken.color.brandBlingPurple200: const Color(0xFFEDDBF9),
    $dinoToken.color.brandBlingPurple300: const Color(0xFFE3CCF4),
    $dinoToken.color.brandBlingPurple400: const Color(0xFFD3B4ED),
    $dinoToken.color.brandBlingPurple500: const Color(0xFFBE93E4),
    $dinoToken.color.brandBlingPurple600: const Color(0xFF8E4EC6),
    $dinoToken.color.brandBlingPurple700: const Color(0xFF8445BC),
    $dinoToken.color.brandBlingPurple800: const Color(0xFF793AAF),
    $dinoToken.color.brandBlingPurple900: const Color(0xFF2B0E44),
    $dinoToken.color.brandBlingViolet25: const Color(0xFFFDFCFE),
    $dinoToken.color.brandBlingViolet50: const Color(0xFFFBFAFF),
    $dinoToken.color.brandBlingViolet75: const Color(0xFFF5F2FF),
    $dinoToken.color.brandBlingViolet100: const Color(0xFFEDE9FE),
    $dinoToken.color.brandBlingViolet200: const Color(0xFFE4DEFC),
    $dinoToken.color.brandBlingViolet300: const Color(0xFFD7CFF9),
    $dinoToken.color.brandBlingViolet400: const Color(0xFFC4B8F3),
    $dinoToken.color.brandBlingViolet500: const Color(0xFFAA99EC),
    $dinoToken.color.brandBlingViolet600: const Color(0xFF6E56CF),
    $dinoToken.color.brandBlingViolet700: const Color(0xFF644FC1),
    $dinoToken.color.brandBlingViolet800: const Color(0xFF5746AF),
    $dinoToken.color.brandBlingViolet900: const Color(0xFF20134B),
    $dinoToken.color.brandBlingIndigo25: const Color(0xFFFDFDFE),
    $dinoToken.color.brandBlingIndigo50: const Color(0xFFF8FAFF),
    $dinoToken.color.brandBlingIndigo75: const Color(0xFFF0F4FF),
    $dinoToken.color.brandBlingIndigo100: const Color(0xFFE6EDFE),
    $dinoToken.color.brandBlingIndigo200: const Color(0xFFD9E2FC),
    $dinoToken.color.brandBlingIndigo300: const Color(0xFFC6D4F9),
    $dinoToken.color.brandBlingIndigo400: const Color(0xFFAEC0F5),
    $dinoToken.color.brandBlingIndigo500: const Color(0xFF8DA4EF),
    $dinoToken.color.brandBlingIndigo600: const Color(0xFF3E63DD),
    $dinoToken.color.brandBlingIndigo700: const Color(0xFF3A5CCC),
    $dinoToken.color.brandBlingIndigo800: const Color(0xFF3451B2),
    $dinoToken.color.brandBlingIndigo900: const Color(0xFF101D46),
    $dinoToken.color.brandBlingBlue25: const Color(0xFFFBFDFF),
    $dinoToken.color.brandBlingBlue50: const Color(0xFFF5FAFF),
    $dinoToken.color.brandBlingBlue75: const Color(0xFFEDF6FF),
    $dinoToken.color.brandBlingBlue100: const Color(0xFFE1F0FF),
    $dinoToken.color.brandBlingBlue200: const Color(0xFFCEE7FE),
    $dinoToken.color.brandBlingBlue300: const Color(0xFFB7D9F8),
    $dinoToken.color.brandBlingBlue400: const Color(0xFF96C7F2),
    $dinoToken.color.brandBlingBlue500: const Color(0xFF5EB0EF),
    $dinoToken.color.brandBlingBlue600: const Color(0xFF0091FF),
    $dinoToken.color.brandBlingBlue700: const Color(0xFF0081F1),
    $dinoToken.color.brandBlingBlue800: const Color(0xFF006ADC),
    $dinoToken.color.brandBlingBlue900: const Color(0xFF00254D),
    $dinoToken.color.brandBlingCyan25: const Color(0xFFFAFDFE),
    $dinoToken.color.brandBlingCyan50: const Color(0xFFF2FCFD),
    $dinoToken.color.brandBlingCyan75: const Color(0xFFE7F9FB),
    $dinoToken.color.brandBlingCyan100: const Color(0xFFD8F3F6),
    $dinoToken.color.brandBlingCyan200: const Color(0xFFC4EAEF),
    $dinoToken.color.brandBlingCyan300: const Color(0xFFAADEE6),
    $dinoToken.color.brandBlingCyan400: const Color(0xFF84CDDA),
    $dinoToken.color.brandBlingCyan500: const Color(0xFF3DB9CF),
    $dinoToken.color.brandBlingCyan600: const Color(0xFF05A2C2),
    $dinoToken.color.brandBlingCyan700: const Color(0xFF0894B3),
    $dinoToken.color.brandBlingCyan800: const Color(0xFF0C7792),
    $dinoToken.color.brandBlingCyan900: const Color(0xFF04313C),
    $dinoToken.color.brandBlingTeal25: const Color(0xFFFAFEFD),
    $dinoToken.color.brandBlingTeal50: const Color(0xFFF1FCFA),
    $dinoToken.color.brandBlingTeal75: const Color(0xFFE7F9F5),
    $dinoToken.color.brandBlingTeal100: const Color(0xFFD9F3EE),
    $dinoToken.color.brandBlingTeal200: const Color(0xFFC7EBE5),
    $dinoToken.color.brandBlingTeal300: const Color(0xFFAFDFD7),
    $dinoToken.color.brandBlingTeal400: const Color(0xFF8DCEC3),
    $dinoToken.color.brandBlingTeal500: const Color(0xFF53B9AB),
    $dinoToken.color.brandBlingTeal600: const Color(0xFF12A594),
    $dinoToken.color.brandBlingTeal700: const Color(0xFF0E9888),
    $dinoToken.color.brandBlingTeal800: const Color(0xFF067A6F),
    $dinoToken.color.brandBlingTeal900: const Color(0xFF10302B),
    $dinoToken.color.brandBlingGreen25: const Color(0xFFFBFEFC),
    $dinoToken.color.brandBlingGreen50: const Color(0xFFF2FCF5),
    $dinoToken.color.brandBlingGreen75: const Color(0xFFE9F9EE),
    $dinoToken.color.brandBlingGreen100: const Color(0xFFDDF3E4),
    $dinoToken.color.brandBlingGreen200: const Color(0xFFCCEBD7),
    $dinoToken.color.brandBlingGreen300: const Color(0xFFB4DFC4),
    $dinoToken.color.brandBlingGreen400: const Color(0xFF92CEAC),
    $dinoToken.color.brandBlingGreen500: const Color(0xFF5BB98C),
    $dinoToken.color.brandBlingGreen600: const Color(0xFF30A46C),
    $dinoToken.color.brandBlingGreen700: const Color(0xFF299764),
    $dinoToken.color.brandBlingGreen800: const Color(0xFF18794E),
    $dinoToken.color.brandBlingGreen900: const Color(0xFF153226),
    $dinoToken.color.brandBlingGrass25: const Color(0xFFFBFEFB),
    $dinoToken.color.brandBlingGrass50: const Color(0xFFF3FCF3),
    $dinoToken.color.brandBlingGrass75: const Color(0xFFEBF9EB),
    $dinoToken.color.brandBlingGrass100: const Color(0xFFDFF3DF),
    $dinoToken.color.brandBlingGrass200: const Color(0xFFCEEBCF),
    $dinoToken.color.brandBlingGrass300: const Color(0xFFB7DFBA),
    $dinoToken.color.brandBlingGrass400: const Color(0xFF97CF9C),
    $dinoToken.color.brandBlingGrass500: const Color(0xFF65BA75),
    $dinoToken.color.brandBlingGrass600: const Color(0xFF46A758),
    $dinoToken.color.brandBlingGrass700: const Color(0xFF3D9A50),
    $dinoToken.color.brandBlingGrass800: const Color(0xFF297C3B),
    $dinoToken.color.brandBlingGrass900: const Color(0xFF1B311E),
    $dinoToken.color.brandBlingBrown25: const Color(0xFFFEFDFC),
    $dinoToken.color.brandBlingBrown50: const Color(0xFFFCF9F6),
    $dinoToken.color.brandBlingBrown75: const Color(0xFFF8F1EA),
    $dinoToken.color.brandBlingBrown100: const Color(0xFFF4E9DD),
    $dinoToken.color.brandBlingBrown200: const Color(0xFFEFDDCC),
    $dinoToken.color.brandBlingBrown300: const Color(0xFFE8CDB5),
    $dinoToken.color.brandBlingBrown400: const Color(0xFFDDB896),
    $dinoToken.color.brandBlingBrown500: const Color(0xFFD09E72),
    $dinoToken.color.brandBlingBrown600: const Color(0xFFAD7F58),
    $dinoToken.color.brandBlingBrown700: const Color(0xFFA07653),
    $dinoToken.color.brandBlingBrown800: const Color(0xFF886349),
    $dinoToken.color.brandBlingBrown900: const Color(0xFF3F2C22),
    $dinoToken.color.brandBlingBronze25: const Color(0xFFFDFCFC),
    $dinoToken.color.brandBlingBronze50: const Color(0xFFFDF8F6),
    $dinoToken.color.brandBlingBronze75: const Color(0xFFF8F1EE),
    $dinoToken.color.brandBlingBronze100: const Color(0xFFF2E8E4),
    $dinoToken.color.brandBlingBronze200: const Color(0xFFEADDD7),
    $dinoToken.color.brandBlingBronze300: const Color(0xFFE0CEC7),
    $dinoToken.color.brandBlingBronze400: const Color(0xFFD1B9B0),
    $dinoToken.color.brandBlingBronze500: const Color(0xFFBFA094),
    $dinoToken.color.brandBlingBronze600: const Color(0xFFA18072),
    $dinoToken.color.brandBlingBronze700: const Color(0xFF977669),
    $dinoToken.color.brandBlingBronze800: const Color(0xFF846358),
    $dinoToken.color.brandBlingBronze900: const Color(0xFF43302B),
    $dinoToken.color.brandBlingGold25: const Color(0xFFFDFDFC),
    $dinoToken.color.brandBlingGold50: const Color(0xFFFBF9F2),
    $dinoToken.color.brandBlingGold75: const Color(0xFFF5F2E9),
    $dinoToken.color.brandBlingGold100: const Color(0xFFEEEADD),
    $dinoToken.color.brandBlingGold200: const Color(0xFFE5DFD0),
    $dinoToken.color.brandBlingGold300: const Color(0xFFDAD1BD),
    $dinoToken.color.brandBlingGold400: const Color(0xFFCBBDA4),
    $dinoToken.color.brandBlingGold500: const Color(0xFFB8A383),
    $dinoToken.color.brandBlingGold600: const Color(0xFF978365),
    $dinoToken.color.brandBlingGold700: const Color(0xFF8C795D),
    $dinoToken.color.brandBlingGold800: const Color(0xFF776750),
    $dinoToken.color.brandBlingGold900: const Color(0xFF3B352B),
    $dinoToken.color.brandBlingSky25: const Color(0xFFF9FEFF),
    $dinoToken.color.brandBlingSky50: const Color(0xFFF1FCFF),
    $dinoToken.color.brandBlingSky75: const Color(0xFFE4F9FF),
    $dinoToken.color.brandBlingSky100: const Color(0xFFD5F4FD),
    $dinoToken.color.brandBlingSky200: const Color(0xFFC1ECF9),
    $dinoToken.color.brandBlingSky300: const Color(0xFFA4DFF1),
    $dinoToken.color.brandBlingSky400: const Color(0xFF79CFEA),
    $dinoToken.color.brandBlingSky500: const Color(0xFF2EBDE5),
    $dinoToken.color.brandBlingSky600: const Color(0xFF68DDFD),
    $dinoToken.color.brandBlingSky700: const Color(0xFF5FD4F4),
    $dinoToken.color.brandBlingSky800: const Color(0xFF0078A1),
    $dinoToken.color.brandBlingSky900: const Color(0xFF003242),
    $dinoToken.color.brandBlingMint25: const Color(0xFFF9FEFD),
    $dinoToken.color.brandBlingMint50: const Color(0xFFEFFEFA),
    $dinoToken.color.brandBlingMint75: const Color(0xFFE1FBF4),
    $dinoToken.color.brandBlingMint100: const Color(0xFFD2F7ED),
    $dinoToken.color.brandBlingMint200: const Color(0xFFC0EFE3),
    $dinoToken.color.brandBlingMint300: const Color(0xFFA5E4D4),
    $dinoToken.color.brandBlingMint400: const Color(0xFF7DD4C0),
    $dinoToken.color.brandBlingMint500: const Color(0xFF40C4AA),
    $dinoToken.color.brandBlingMint600: const Color(0xFF70E1C8),
    $dinoToken.color.brandBlingMint700: const Color(0xFF69D9C1),
    $dinoToken.color.brandBlingMint800: const Color(0xFF147D6F),
    $dinoToken.color.brandBlingMint900: const Color(0xFF09342E),
    $dinoToken.color.brandBlingLime25: const Color(0xFFFCFDFA),
    $dinoToken.color.brandBlingLime50: const Color(0xFFF7FCF0),
    $dinoToken.color.brandBlingLime75: const Color(0xFFEEFADC),
    $dinoToken.color.brandBlingLime100: const Color(0xFFE4F7C7),
    $dinoToken.color.brandBlingLime200: const Color(0xFFD7F2B0),
    $dinoToken.color.brandBlingLime300: const Color(0xFFC9E894),
    $dinoToken.color.brandBlingLime400: const Color(0xFFB1D16A),
    $dinoToken.color.brandBlingLime500: const Color(0xFF94BA2C),
    $dinoToken.color.brandBlingLime600: const Color(0xFF99D52A),
    $dinoToken.color.brandBlingLime700: const Color(0xFF93C926),
    $dinoToken.color.brandBlingLime800: const Color(0xFF5D770D),
    $dinoToken.color.brandBlingLime900: const Color(0xFF263209),
    $dinoToken.color.brandBlingYellow25: const Color(0xFFFDFDF9),
    $dinoToken.color.brandBlingYellow50: const Color(0xFFFFFCE8),
    $dinoToken.color.brandBlingYellow75: const Color(0xFFFFFBD1),
    $dinoToken.color.brandBlingYellow100: const Color(0xFFFFF8BB),
    $dinoToken.color.brandBlingYellow200: const Color(0xFFFEF2A4),
    $dinoToken.color.brandBlingYellow300: const Color(0xFFF9E68C),
    $dinoToken.color.brandBlingYellow400: const Color(0xFFEFD36C),
    $dinoToken.color.brandBlingYellow500: const Color(0xFFEBBC00),
    $dinoToken.color.brandBlingYellow600: const Color(0xFFF5D90A),
    $dinoToken.color.brandBlingYellow700: const Color(0xFFF7CE00),
    $dinoToken.color.brandBlingYellow800: const Color(0xFF946800),
    $dinoToken.color.brandBlingYellow900: const Color(0xFF35290F),
    $dinoToken.color.brandBlingAmber25: const Color(0xFFFEFDFB),
    $dinoToken.color.brandBlingAmber50: const Color(0xFFFFF9ED),
    $dinoToken.color.brandBlingAmber75: const Color(0xFFFFF4D5),
    $dinoToken.color.brandBlingAmber100: const Color(0xFFFFECBC),
    $dinoToken.color.brandBlingAmber200: const Color(0xFFFFE3A2),
    $dinoToken.color.brandBlingAmber300: const Color(0xFFFFD386),
    $dinoToken.color.brandBlingAmber400: const Color(0xFFF3BA63),
    $dinoToken.color.brandBlingAmber500: const Color(0xFFEE9D2B),
    $dinoToken.color.brandBlingAmber600: const Color(0xFFFFB224),
    $dinoToken.color.brandBlingAmber700: const Color(0xFFFFA01C),
    $dinoToken.color.brandBlingAmber800: const Color(0xFFAD5700),
    $dinoToken.color.brandBlingAmber900: const Color(0xFF4E2009),
    $dinoToken.color.brandBlingRuby25: const Color(0xFFFFFCFD),
    $dinoToken.color.brandBlingRuby50: const Color(0xFFFFF7F9),
    $dinoToken.color.brandBlingRuby75: const Color(0xFFFEEFF3),
    $dinoToken.color.brandBlingRuby100: const Color(0xFFFDE5EA),
    $dinoToken.color.brandBlingRuby200: const Color(0xFFFAD8E0),
    $dinoToken.color.brandBlingRuby300: const Color(0xFFF5C7D1),
    $dinoToken.color.brandBlingRuby400: const Color(0xFFEEAFBC),
    $dinoToken.color.brandBlingRuby500: const Color(0xFFE592A2),
    $dinoToken.color.brandBlingRuby600: const Color(0xFFE54666),
    $dinoToken.color.brandBlingRuby700: const Color(0xFFDA3A5C),
    $dinoToken.color.brandBlingRuby800: const Color(0xFFCA244D),
    $dinoToken.color.brandBlingRuby900: const Color(0xFF64172B),
    $dinoToken.color.brandBlingIris25: const Color(0xFFFDFDFF),
    $dinoToken.color.brandBlingIris50: const Color(0xFFFAFAFF),
    $dinoToken.color.brandBlingIris75: const Color(0xFFF3F3FF),
    $dinoToken.color.brandBlingIris100: const Color(0xFFEBEBFE),
    $dinoToken.color.brandBlingIris200: const Color(0xFFE0E0FD),
    $dinoToken.color.brandBlingIris300: const Color(0xFFD0D0FA),
    $dinoToken.color.brandBlingIris400: const Color(0xFFBABBF5),
    $dinoToken.color.brandBlingIris500: const Color(0xFF9B9EF0),
    $dinoToken.color.brandBlingIris600: const Color(0xFF5B5BD6),
    $dinoToken.color.brandBlingIris700: const Color(0xFF5353CE),
    $dinoToken.color.brandBlingIris800: const Color(0xFF4747C2),
    $dinoToken.color.brandBlingIris900: const Color(0xFF272962),
    $dinoToken.color.brandBlingJade25: const Color(0xFFFBFEFD),
    $dinoToken.color.brandBlingJade50: const Color(0xFFEFFDF6),
    $dinoToken.color.brandBlingJade75: const Color(0xFFE4FAEF),
    $dinoToken.color.brandBlingJade100: const Color(0xFFD7F4E6),
    $dinoToken.color.brandBlingJade200: const Color(0xFFC6ECDB),
    $dinoToken.color.brandBlingJade300: const Color(0xFFB0E0CC),
    $dinoToken.color.brandBlingJade400: const Color(0xFF8FCFB9),
    $dinoToken.color.brandBlingJade500: const Color(0xFF56BA9F),
    $dinoToken.color.brandBlingJade600: const Color(0xFF29A383),
    $dinoToken.color.brandBlingJade700: const Color(0xFF259678),
    $dinoToken.color.brandBlingJade800: const Color(0xFF1A7A5E),
    $dinoToken.color.brandBlingJade900: const Color(0xFF1D3B31),
  }.expand,
  spaces: {
    $dinoToken.spacing.spacingnone: 0,
    $dinoToken.spacing.spacing50: 2,
    $dinoToken.spacing.spacing75: 4,
    $dinoToken.spacing.spacing100: 8, // spacing75 * 2
    $dinoToken.spacing.spacing200: 10,
    $dinoToken.spacing.spacing300: 12, // spacing100 + spacing75
    $dinoToken.spacing.spacing400: 16, // spacing300 + spacing75
    $dinoToken.spacing.spacing500: 20, // spacing400 + spacing75
    $dinoToken.spacing.spacing600: 24, // spacing500 + spacing75
    $dinoToken.spacing.spacing700: 32, // spacing600 + spacing100
    $dinoToken.spacing.spacing800: 40, // spacing700 + spacing100
    $dinoToken.spacing.spacing900: 48, // spacing800 + spacing100
    $dinoToken.spacing.spacing1000: 72, // spacing900 + spacing600
  },
  radii: {
    $dinoToken.radius.none: const Radius.circular(4),
    $dinoToken.radius.xxsmall: const Radius.circular(8),
    $dinoToken.radius.xsmall: const Radius.circular(12),
    $dinoToken.radius.small: const Radius.circular(16),
    $dinoToken.radius.medium: const Radius.circular(20),
    $dinoToken.radius.large: const Radius.circular(24),
    $dinoToken.radius.xlarge: const Radius.circular(28),
    $dinoToken.radius.xxlarge: const Radius.circular(28),
    $dinoToken.radius.circle: const Radius.circular(9999),
  },
);

extension ColorExpand on Map<ColorToken, Color> {
  Map<ColorToken, Color> get expand {
    addAll({
      $dinoToken.color.primary: this[$dinoToken.color.brandBlingPurple500]!,
      $dinoToken.color.primarySub: this[$dinoToken.color.brandBlingViolet300]!,
      
      $dinoToken.color.sementicPrimary: this[$dinoToken.color.blingPrimary600]!,
      $dinoToken.color.sementicPrimarySub:
          this[$dinoToken.color.brandBlingOranage700]!,
    });
    return this;
  }
}
