workflows:
  flutter-app:
    name: Flutter App
    environment:
      flutter: 3.29.1
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/.gradle
        - ~/.cocoapods
        - pubspec.lock
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
    scripts:
      - name: Flutter analyze
        script: flutter analyze
      - name: Flutter test
        script: flutter test
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
      - name: Build Android
        script: |
          flutter build appbundle --release
    artifacts:
      - build/ios/ipa/*.ipa
      - build/app/outputs/bundle/release/app-release.aab