workflows:
  ios-android-release:
    name: iOS & Android Release
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.devdino.travelee
      flutter: stable
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: "v*.*.*"
          include: true
    scripts:
      - name: Set build number
        script: |
          BUILD_NUMBER=$(($(date +%s) / 60))
          echo "Build number: $BUILD_NUMBER"

      - name: Flutter build iOS
        script: |
          flutter build ios --release \
            --build-number=$BUILD_NUMBER

      - name: Flutter build Android
        script: |
          flutter build appbundle --release \
            --build-number=$BUILD_NUMBER

      # - name: iOS code signing and packaging
      #   script: |
      #     cd ios
      #     xcode-project use-profiles
      #     xcode-project build-ipa \
      #       --workspace Runner.xcworkspace \
      #       --scheme Runner

    artifacts:
      - build/ios/ipa/*.ipa
      - build/app/outputs/bundle/release/app-release.aab
      - flutter_drive.log

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_KEY
        submit_to_testflight: true
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT
        track: internal