name: travelee
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  mix: ^1.5.2
  design_systems:
    path: ../../packages/design_systems
  utils:
    path: ../../packages/utils
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9 # SVG 이미지 렌더링

  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.5

  dio: ^5.4.1 # HTTP 클라이언트, REST API 통신
  shared_preferences: ^2.2.2 # 로컬 데이터 저장

  go_router: ^13.2.5

  flutter_native_splash: ^2.4.0 # 네이티브 스플래시 스크린 생성

  url_launcher: ^6.2.5 # 외부 URL 실행
  easy_debounce: ^2.0.3 # 연속 이벤트 제어
  talker: ^3.2.0
  talker_flutter: ^3.6.0
  talker_logger: ^3.1.0
  sugar: ^2.4.1
  permission_handler: ^11.4.0
  syncfusion_flutter_datepicker: ^24.2.9 # 최신 버전으로 업데이트
  country_picker: ^2.0.27 # 국가 선택
  flutter_localizations:
    sdk: flutter

  uuid: ^4.2.2
  country_icons: ^3.0.0
  equatable: ^2.0.5
  intl: ^0.19.0
  collection: ^1.18.0
  sqflite: ^2.3.0
  path: ^1.8.3

  flutter_map: ^6.2.1
  latlong2: ^0.9.0
  http: ^1.3.0

  dotted_border: ^2.1.0

  supabase_flutter: ^2.3.4
  flutter_dotenv: ^5.2.1

  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  firebase_messaging: ^15.2.6
  google_sign_in: ^6.2.4
  google_mobile_ads: ^6.0.0

  pdf: ^3.10.7
  path_provider: ^2.1.2
  share_plus: ^7.2.2
  sign_in_with_apple: ^7.0.1

  package_info_plus: ^8.3.0

  webview_flutter: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.14
  riverpod_generator: ^2.4.0
  nitrogen: ^0.4.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 23 # Google Mobile Ads 요구사항
  remove_alpha_ios: true
  
flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/privacyPolicy_k.html
    - assets/privacyPolicy_e.html
    - assets/termsOfService_k.html
    - assets/termsOfService_e.html
    - .env # 환경 변수
    - assets/fonts/NotoSansKR-Regular.ttf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
