name: design_systems
description: "디자인 시스템"
version: 0.0.1

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mix: ^1.5.2
  flutter_svg:
  nitrogen_types:
  nitrogen_flutter_svg:
  nitrogen_lottie:
  scroll_to_index:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:
  nitrogen:

flutter:
  assets:
    # icons
    - assets/icons/arrow_down.svg
    - assets/icons/arrow_up.svg
    - assets/icons/checkbox_on.svg
    - assets/icons/checkbox_off.svg
    - assets/icons/close.svg
    - assets/icons/filter.svg
    - assets/icons/letter.svg
    - assets/icons/clock.svg
    - assets/icons/refresh.svg
    - assets/icons/toast_check.svg
    - assets/icons/toast_close.svg
    # images
    - assets/images/clap.png

  fonts:
    # - family: RiaSans-ExtraBold
    #   fonts:
    #     - asset: assets/fonts/RiaSans-ExtraBold.otf
    #       style: italic
    - family: Pretendard
      fonts:
        - asset: assets/fonts/pretendard/Pretendard-Black.otf
          weight: 100
        - asset: assets/fonts/pretendard/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/pretendard/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/pretendard/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/pretendard/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/pretendard/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/pretendard/Pretendard-Black.otf
          weight: 900
